# Generated by Django 6.1.1 on 2026-09-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('energy_kcal', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('serving_size_g', models.DecimalField(blank=True, decimal_places=1, help_text='Grams in one natural serving, e.g. one medium banana.', max_digits=6, null=True)),
                ('serving_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null means this is a shared library food.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('amount_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20)),
                ('consumed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='nutrition.food')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log', to='organizations.organization')),
            ],
            options={
                'ordering': ['consumed_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('name', models.CharField(default='Daily targets', max_length=255)),
                ('target_kcal', models.PositiveIntegerField()),
                ('target_protein_g', models.PositiveSmallIntegerField()),
                ('target_carbs_g', models.PositiveSmallIntegerField()),
                ('target_fat_g', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_shared_food_slug'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_org_food_slug'),
        ),
        migrations.AddConstraint(
            model_name='nutritionplan',
            constraint=models.UniqueConstraint(fields=('organization', 'user_id'), name='one_nutrition_plan_per_user'),
        ),
    ]
