# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL('DROP INDEX IF EXISTS "unique_shared_food_slug";', migrations.RunSQL.noop)],
            state_operations=[migrations.RemoveConstraint(model_name='food', name='unique_shared_food_slug')],
        ),
        migrations.AlterField(
            model_name='food',
            name='academy',
            field=models.ForeignKey(blank=True, help_text='Null means this is a shared library food.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='foodlogentry',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='organizations.academy'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(condition=models.Q(('academy__isnull', True)), fields=('slug',), name='unique_shared_food_slug'),
        ),
    ]
