# Generated by Django 6.1.1 on 2026-09-10 10:40

import django.db.models.deletion
from django.db import migrations, models



APP = "nutrition"
OWNED = [("foodlogentry", "student"), ("nutritionplan", "student")]


def spread_across_members(apps, schema_editor):
    """Give every orphaned row a member to belong to.

    These were keyed to a login. Most members have none, which is the whole
    reason for the change, so there is nothing to match on — a demo row is
    handed to a member of its own academy, and a real one to nobody.
    """
    Student = apps.get_model("students", "Student")
    for model_name, _ in OWNED:
        model = apps.get_model(APP, model_name)
        by_academy = {}
        for row in model.objects.all():
            members = by_academy.get(row.academy_id)
            if members is None:
                members = list(
                    Student.objects.filter(academy_id=row.academy_id).order_by("id")
                )
                by_academy[row.academy_id] = members
            if not members:
                row.delete()
                continue
            row.student_id = members[row.pk % len(members)].id
            row.save(update_fields=["student_id"])


def unspread(apps, schema_editor):
    """Nothing to undo — user_id is restored empty by the reverse AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_food_unique_shared_food_slug_and_more'),
        ('organizations', '0014_branch_closed_on'),
        ('students', '0007_student_invited_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nutritionplan',
            name='one_nutrition_plan_per_user',
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_log', to='students.student'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='students.student'),
        ),
        migrations.RunPython(spread_across_members, unspread),
        migrations.AddConstraint(
            model_name='nutritionplan',
            constraint=models.UniqueConstraint(fields=('academy', 'student'), name='one_nutrition_plan_per_member'),
        ),
        migrations.RemoveField(
            model_name='foodlogentry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='user_id',
        ),
    ]
