# Generated by Django 6.1.1 on 2026-09-07 20:08

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_membership_requires_payment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.member_photo_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('left', 'Left')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN card'), ('passport', 'Passport'), ('driving_licence', 'Driving licence'), ('voter_id', 'Voter ID'), ('student_id', 'Student ID'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=students.models.member_document_path)),
                ('number_last4', models.CharField(blank=True, help_text='Last four digits only. The full number is never stored.', max_length=4)),
                ('uploaded_by', models.CharField(blank=True, max_length=64)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_documents', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
