# Generated by Django 6.1.1 on 2026-09-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_above_academy'),
        ('students', '0005_alter_memberdocument_academy_alter_student_academy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('requested_by', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.CharField(blank=True, max_length=64)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_transfers', to='organizations.academy')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='organizations.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='organizations.branch')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student',), name='one_open_transfer_per_member')],
            },
        ),
    ]
