# Generated by Django 6.1.1 on 2026-09-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_membertransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When the academy invited them to sign in. Only an invited record can be claimed: an email here is a contact detail the desk typed in, not a grant of access.', null=True),
        ),
    ]
