# Generated by Django 6.1.1 on 2026-09-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('colour', models.CharField(blank=True, max_length=9)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='organizations.organization')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fought_on', models.DateField()),
                ('opponent_name', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('points_for', models.PositiveSmallIntegerField(default=0)),
                ('points_against', models.PositiveSmallIntegerField(default=0)),
                ('event', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('opponent_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouts_against', to='students.student')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='students.student')),
            ],
            options={
                'ordering': ['-fought_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('examiner', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradings', to='karate.belt')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gradings', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='organizations.organization')),
            ],
            options={
                'ordering': ['-held_on'],
            },
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('absent', 'Absent')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('grading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='karate.grading')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='belt',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_belt_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='gradingresult',
            constraint=models.UniqueConstraint(fields=('grading', 'student'), name='one_result_per_student_per_grading'),
        ),
    ]
