# Generated by Django 6.1.1 on 2026-09-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grading',
            options={'ordering': ['-held_on', '-id']},
        ),
        migrations.AlterModelOptions(
            name='gradingresult',
            options={'ordering': ['id']},
        ),
    ]
