# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0003_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='organizations.academy'),
        ),
    ]
