# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeplan',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.academy'),
        ),
    ]
