# Generated by Django 6.1.1 on 2026-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['email']},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation was claimed.', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.CharField(blank=True, default='', help_text='Supabase user id. Empty until an invited person first signs in.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id', ''), _negated=True), fields=('organization', 'user_id'), name='one_membership_per_user_per_org'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('organization', 'email'), name='one_membership_per_email_per_org'),
        ),
    ]
