# Generated by Django 6.1.1 on 2026-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_split_fitness_from_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff / Trainer'), ('member', 'Member')], max_length=20),
        ),
    ]
