# Generated by Django 6.1.1 on 2026-09-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='membership_requires_payment',
            field=models.BooleanField(default=True),
        ),
    ]
