# Generated by Django 6.1.1 on 2026-09-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_membership_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='one_primary_branch_per_org'),
        ),
    ]
