# Generated by Django 6.1.1 on 2026-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_above_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='verticals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
