# Generated by Django 6.1.1 on 2026-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_branch_assignment_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
