# Generated by Django 6.1.1 on 2026-09-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolment',
            options={'ordering': ['-enrolled_on', '-id']},
        ),
    ]
