# Generated by Django 6.1.1 on 2026-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_alter_batch_academy'),
        ('organizations', '0014_branch_closed_on'),
        ('students', '0006_membertransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waitlisted', 'Waiting'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', "Didn't turn up")], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='organizations.academy')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='batches.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='students.student')),
            ],
            options={
                'ordering': ['session_date', 'booked_at', 'id'],
                'indexes': [models.Index(fields=['batch', 'session_date'], name='batches_cla_batch_i_2f4f55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'waitlisted'])), fields=('batch', 'student', 'session_date'), name='one_open_booking_per_session')],
            },
        ),
    ]
