# Generated by Django 6.1.1 on 2026-09-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_classbooking'),
        ('organizations', '0014_branch_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_coached', to='organizations.membership'),
        ),
    ]
