# Generated by Django 6.1.1 on 2026-09-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_batch_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('waitlisted', 'Waiting'), ('cancelled', 'Cancelled'), ('skipped', 'Not coming'), ('attended', 'Attended'), ('no_show', "Didn't turn up")], default='booked', max_length=20),
        ),
    ]
