# Generated by Django 6.1.1 on 2026-09-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('organizations', '0005_alter_membership_role'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half yearly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField(help_text='How long a subscription on this tier lasts.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes_personal_trainer', models.BooleanField(default=False)),
                ('class_credits_per_week', models.PositiveSmallIntegerField(blank=True, help_text='Bookable class slots per week. Blank means unlimited.', null=True)),
                ('perks', models.JSONField(blank=True, default=list, help_text='Free-text perks shown on the plan.')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='organizations.organization')),
            ],
            options={
                'ordering': ['position', 'price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='students.student')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.membershiptier')),
            ],
            options={
                'ordering': ['-expires_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='membershiptier',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_tier_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['organization', 'expires_on'], name='subscriptio_organiz_85c315_idx'),
        ),
    ]
