# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_feeplan_academy_alter_invoice_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
        ('students', '0005_alter_memberdocument_academy_alter_student_academy'),
        ('subscriptions', '0002_rename_organization_to_academy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membersubscription',
            name='subscriptio_organiz_85c315_idx',
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.academy'),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['academy', 'expires_on'], name='subscriptio_academy_578adf_idx'),
        ),
    ]
