# Generated by Django 6.1.1 on 2026-09-08 16:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_branch_closed_on'),
        ('students', '0006_membertransfer'),
        ('subscriptions', '0003_remove_membersubscription_subscriptio_organiz_85c315_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='organizations.academy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='students.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organizations.membership')),
            ],
            options={
                'ordering': ['-started_on', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('student',), name='one_running_trainer_per_member')],
            },
        ),
    ]
