# Generated by Django 6.1.1 on 2026-09-07 08:53

import bodylog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=bodylog.models.progress_photo_path)),
                ('pose', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], default='front', max_length=10)),
                ('taken_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='organizations.organization')),
            ],
            options={
                'ordering': ['-taken_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('metric', models.CharField(choices=[('weight', 'Body Weight'), ('body_fat', 'Body Fat'), ('neck', 'Neck'), ('shoulders', 'Shoulders'), ('chest', 'Chest'), ('waist', 'Waist'), ('hips', 'Hips'), ('bicep_left', 'Bicep (left)'), ('bicep_right', 'Bicep (right)'), ('forearm_left', 'Forearm (left)'), ('forearm_right', 'Forearm (right)'), ('thigh_left', 'Thigh (left)'), ('thigh_right', 'Thigh (right)'), ('calf_left', 'Calf (left)'), ('calf_right', 'Calf (right)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('cm', 'cm'), ('in', 'in'), ('percent', '%')], max_length=10)),
                ('measured_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='organizations.organization')),
            ],
            options={
                'ordering': ['-measured_on'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user_id', 'metric', 'measured_on'), name='one_reading_per_metric_per_day')],
            },
        ),
    ]
