# Generated by Django 6.1.1 on 2026-09-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('website', 'Website'), ('referral', 'Referral'), ('social', 'Social media'), ('other', 'Other')], default='walk_in', max_length=20)),
                ('interested_in', models.CharField(blank=True, help_text='Vertical or programme they asked about.', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial scheduled'), ('trial_done', 'Trial done'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('trial_on', models.DateField(blank=True, null=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='organizations.branch')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
