# Generated by Django 6.1.1 on 2026-09-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='converted_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_enquiry', to='students.student'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='organizations.organization'),
        ),
    ]
