# Generated by Django 6.1.1 on 2026-09-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'enquiries'},
        ),
    ]
