# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='organizations.academy'),
        ),
    ]
