# Generated by Django 6.1.1 on 2026-09-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lane_count', models.PositiveSmallIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaneBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.PositiveSmallIntegerField()),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0 = Monday .. 6 = Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lane_bookings', to='batches.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_bookings', to='organizations.organization')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='swimming.pool')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'lane_number'],
            },
        ),
        migrations.CreateModel(
            name='SwimLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_levels', to='organizations.organization')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SwimSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='swimming.swimlevel')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateField()),
                ('assessed_by', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_assessments', to='students.student')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='swimming.swimskill')),
            ],
            options={
                'ordering': ['-achieved_on'],
                'constraints': [models.UniqueConstraint(fields=('student', 'skill'), name='one_assessment_per_skill_per_student')],
            },
        ),
    ]
