# Generated by Django 6.1.1 on 2026-09-08 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_membership_requires_payment'),
        ('students', '0003_student_qr_token'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('qr', 'QR code'), ('manual', 'Front desk'), ('biometric', 'Biometric')], default='manual', max_length=20)),
                ('admitted', models.BooleanField(default=True)),
                ('refused_reason', models.CharField(blank=True, choices=[('no_membership', 'No membership'), ('awaiting_payment', 'Payment not taken'), ('expired', 'Membership expired'), ('cancelled', 'Membership cancelled'), ('not_started', "Membership hasn't started")], max_length=30)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='students.student')),
                ('subscription', models.ForeignKey(blank=True, help_text='The membership that admitted them, when one did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='subscriptions.membersubscription')),
            ],
            options={
                'ordering': ['-checked_in_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-checked_in_at'], name='checkins_ch_organiz_f5cdaa_idx'), models.Index(fields=['student', '-checked_in_at'], name='checkins_ch_student_46b017_idx')],
            },
        ),
    ]
