# Generated by Django 6.1.1 on 2026-09-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_checkin'),
        ('organizations', '0006_membership_requires_payment'),
        ('students', '0003_student_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=64)),
                ('external_id', models.CharField(help_text="The reader's own user number.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrolments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrolments', to='students.student')),
            ],
            options={
                'ordering': ['device', 'external_id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'device', 'external_id'), name='one_member_per_reader_id')],
            },
        ),
    ]
