# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
        ('students', '0004_rename_organization_to_academy'),
        ('subscriptions', '0002_rename_organization_to_academy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkin',
            name='attendance__organiz_c844b3_idx',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='biometricenrolment',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrolments', to='organizations.academy'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='organizations.academy'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['academy', '-checked_in_at'], name='attendance__academy_3046e0_idx'),
        ),
    ]
