# Generated by Django 6.1.1 on 2026-09-07 08:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='progression',
            field=models.CharField(choices=[('none', 'None — repeat the same targets'), ('linear', 'Linear — add weight when every set hits the target'), ('double_progression', 'Double progression — add reps to the top of the range, then weight'), ('greyskull', 'Greyskull LP — last set is AMRAP, double the jump on a big set')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='routine',
            name='progression_increment',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='How much weight to add when the rule says to progress.', max_digits=5),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='superset_group',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Items sharing a group are performed back-to-back with no rest between them.', null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_reps_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Top of the rep range. Double progression needs this; other rules ignore it.', null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='estimated_1rm',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='is_personal_record',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='setlog',
            name='is_warmup',
            field=models.BooleanField(default=False, help_text='Warm-ups are excluded from personal records and progression.'),
        ),
        migrations.AddField(
            model_name='setlog',
            name='rir',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Reps in reserve — how many were left in the tank.', null=True),
        ),
    ]
