# Generated by Django 6.1.1 on 2026-09-10 10:40

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_invited_at'),
        ('workouts', '0004_rename_organization_to_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='students.student'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='students.student'),
        ),
    ]
