# Generated by Django 6.1.1 on 2026-09-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='strength', max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('band', 'Resistance Band'), ('other', 'Other')], default='other', max_length=20)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('upper_back', 'Upper Back'), ('lats', 'Lats'), ('lower_back', 'Lower Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('glutes', 'Glutes'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('adductors', 'Adductors'), ('abductors', 'Abductors'), ('neck', 'Neck'), ('full_body', 'Full Body')], max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null means this is a shared library exercise, visible to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_shared_exercise_slug'), models.UniqueConstraint(fields=('organization', 'slug'), name='unique_org_exercise_slug')],
            },
        ),
    ]
