# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_organization_to_academy'),
        ('organizations', '0009_rename_organization_to_academy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL('DROP INDEX IF EXISTS "unique_shared_exercise_slug";', migrations.RunSQL.noop)],
            state_operations=[migrations.RemoveConstraint(model_name='exercise', name='unique_shared_exercise_slug')],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='academy',
            field=models.ForeignKey(blank=True, help_text='Null means this is a shared library exercise, visible to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='organizations.academy'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('academy__isnull', True)), fields=('slug',), name='unique_shared_exercise_slug'),
        ),
    ]
